// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Robot_Simulation.Data;

#nullable disable

namespace Robot_Simulation.Migrations
{
    [DbContext(typeof(RobotSimulationContext))]
    [Migration("20260517171542_AddPackageCreatedOnDay")]
    partial class AddPackageCreatedOnDay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Robot_Simulation.Models.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("int");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Robot_Simulation.Models.Packages", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("BatteryCost")
                        .HasColumnType("real");

                    b.Property<int>("CreatedOnDay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("StorageTime")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WareHouseId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WareHouseId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Robot_Simulation.Models.Robot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MaintenanceFee")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("WareHouseId")
                        .HasColumnType("int");

                    b.Property<string>("robot_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("ID");

                    b.HasIndex("WareHouseId");

                    b.ToTable("Robots");

                    b.HasDiscriminator<string>("robot_type").HasValue("robot");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Robot_Simulation.Models.WareHouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MaitananceFee")
                        .HasColumnType("int");

                    b.Property<int>("StorgarSize")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("WareHouses");
                });

            modelBuilder.Entity("Robot_Simulation.Models.WarehouseUpgrade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpgradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WareHouseId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WareHouseId");

                    b.ToTable("WarehouseUpgradePurchases");
                });

            modelBuilder.Entity("Robot_Simulation.Models.ChargingRobot", b =>
                {
                    b.HasBaseType("Robot_Simulation.Models.Robot");

                    b.Property<float>("ChargingSpeed")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("charging");
                });

            modelBuilder.Entity("Robot_Simulation.Models.PackingRobot", b =>
                {
                    b.HasBaseType("Robot_Simulation.Models.Robot");

                    b.Property<float>("BatteryLevel")
                        .HasColumnType("real");

                    b.Property<int>("PackingSpeed")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("packing");
                });

            modelBuilder.Entity("Robot_Simulation.Models.Game", b =>
                {
                    b.HasOne("Robot_Simulation.Models.WareHouse", "WareHouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("Robot_Simulation.Models.Packages", b =>
                {
                    b.HasOne("Robot_Simulation.Models.WareHouse", "WareHouse")
                        .WithMany("Packages")
                        .HasForeignKey("WareHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("Robot_Simulation.Models.Robot", b =>
                {
                    b.HasOne("Robot_Simulation.Models.WareHouse", "WareHouse")
                        .WithMany("Robots")
                        .HasForeignKey("WareHouseId");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("Robot_Simulation.Models.WarehouseUpgrade", b =>
                {
                    b.HasOne("Robot_Simulation.Models.WareHouse", "WareHouse")
                        .WithMany("UpgradesPurchased")
                        .HasForeignKey("WareHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("Robot_Simulation.Models.WareHouse", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("Robots");

                    b.Navigation("UpgradesPurchased");
                });
#pragma warning restore 612, 618
        }
    }
}
